wse_project:
  outputs:
    dev:
      dataset: wse_dev
      fixed_retries: 1
      keyfile: /home/skibooj/.google/credentials/google_credentials.json
      location: europe-west6
      method: service-account
      priority: interactive
      project: wse-data-345914
      threads: 4
      timeout_seconds: 300
      type: bigquery
    prod:
      dataset: wse_prod
      fixed_retries: 1
      keyfile: /home/skibooj/.google/credentials/google_credentials.json
      location: europe-west6
      method: service-account
      priority: interactive
      project: wse-data-345914
      threads: 4
      timeout_seconds: 300
      type: bigquery
  target: dev